### ISSUE TITLE
Feature: Installation on Python 3.6.6

### ISSUE THREAD

**Issue by airmonitor** [awslabs/cfn-python-lint#368] opened 2018-09-26 09:10 UTC
*cfn-lint version: 0.7.3

Installation in python 3.6.6 is failing.
Is there any plan to include python 3.6+ as supported version as well?

Regards.

**Comment by cmmeyer** [comment] 2018-09-26 15:12
Hi! What's the message your seeing?  Is this via pip?

**Comment by airmonitor** [comment] 2018-09-27 06:37
Hi cmmeyer,
Thx for reply.
[install_log.txt](https://github.com/awslabs/cfn-python-lint/files/2422743/install_log.txt)

I've attached full installation log from pipenv.

**Comment by cmmeyer** [comment] 2018-09-27 16:33
```
Could not find a version that matches botocore<1.11.0,<1.13.0,>=1.12.11
```

Hmm... that seems like a hard set of criteria to meet.  Thanks.

**Comment by fatbasstard** [comment] 2018-09-27 16:34
Since the linter itself does nothing. this could be coming from SAM...

**Comment by fatbasstard** [comment] 2018-10-11 14:57
FYI: we're working with the linter in Python 3.6 now. I really got the feeling it's a Python dependency thing going on on your system. Can you check which boto version you've got installed (global) on your system @airmonitor ?

**Comment by airmonitor** [comment] 2018-10-12 14:05
Hey.

It seems that problem is resolved somehow.
Today installation in venv completed successfully with python 3.6.6

**Comment by cmmeyer** [comment] 2018-10-12 14:07
Great news! We were having a heck of a time reproducing it. Ok to close the issue.

**Closed** 2018-10-26 05:00 UTC
Labels: enhancement
